// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyysvowdxdrkatxdmhod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5eXN2b3dkeGRya2F0eGRtaG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTYwNjAsImV4cCI6MjA3MTU3MjA2MH0.RuI2TzuFhCxSJ5FFbJBRYy8ou6Gbr0-yKduLQzvXkKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});